[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_market_hours = "32RNH2JPGUCGdYp5TetkT1Y2CHwAUk2XzXn6VCFqvb7F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
